apiVersion: v1
kind: Service
metadata:
  name: {{ include "pwa-infra.fullname" . }}
  labels: {{- include "pwa-infra.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: tcp-8080
  internalTrafficPolicy: Cluster
  selector:
    {{ include "pwa-infra.selectorLabels" . | nindent 4 }}
