apiVersion: v1
kind: Service
metadata:
  name: pwa-frontend
  labels:
    app: pwa-frontend
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: 80-http
  selector:
    app: pwa-frontend
