apiVersion: v1
kind: Service
metadata:
  name: pwa-backend
  labels:
    app: pwa-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: tcp-8080
  internalTrafficPolicy: Cluster
  selector:
    app: pwa-backend
