apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pwa-infra.fullname" . }}-allow-from-openshift-ingress
  labels: {{ include "pwa-infra.labels" . | nindent 4 }}
spec:
  # This policy allows any pod with a route & service combination
  # to accept traffic from the OpenShift router pods. This is
  # required for things outside of OpenShift (like the Internet)
  # to reach your pods.
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pwa-infra.fullname" . }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pwa-infra.fullname" . }}-allow-same-namespace
  labels: {{ include "pwa-infra.labels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
  policyTypes:
    - Ingress