kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ template "pwa-infra.fullname" . }}
  labels: {{ include "pwa-infra.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.route.iprestricted }}
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.route.ipallowlist | join " " | quote }}
  {{- end}}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ template "pwa-infra.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: 80-http
